version: "3.8"

networks:
  kowan:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - kowan
    restart: unless-stopped
    depends_on:
      - service

  service:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - kowan
    volumes:
      - ./src/log:/usr/src/app/src/log
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - kowan:/var/lib/postgresql/data
    networks:
      - kowan

volumes:
  kowan:
